#:schema node_modules/wrangler/config-schema.json
name = "eoc-stateless-peer-websocket"
compatibility_date = "2024-07-01"

main = "src/index.mjs"

[durable_objects]
bindings = [
  { name = "rooms", class_name = "ChatRoom" },
  { name = "limiters", class_name = "RateLimiter" }
]

[[rules]]
type = "Data"
globs = ["**/*.html", "**/*.svg"]
fallthrough = false

# Indicate that you want the ChatRoom and RateLimiter classes to be callable as Durable Objects.
[[migrations]]
tag = "v1" # Should be unique for each entry
new_classes = ["ChatRoom", "RateLimiter"]
